package com.msploit.instrument;

import java.awt.event.KeyEvent;
import java.io.File;
import java.lang.instrument.Instrumentation;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author myles
 */
public class AgentForm extends javax.swing.JFrame {
    private Instrumentation  instrumentation;
    private DefaultListModel blackListClasses;
    /**
     * Creates new form AgentForm
     */
    public AgentForm() {
        initComponents();
        blackListClasses = new DefaultListModel();
        jList1.setModel(blackListClasses);
        blackListClasses.add(0, "java/");
        blackListClasses.add(0, "javax/");
        blackListClasses.add(0, "sun/");
        blackListClasses.add(0, "apple/");
        blackListClasses.add(0, "com/sun");
        blackListClasses.add(0, "com/apple");
        
    }
    
    public void loadInstrumentor(Instrumentation inst) {
        instrumentation = inst;       
    }
    
    private void activateInstrumentor(ArrayList<String> list) {
        instrumentation.addTransformer(new SimpleTransformer(list));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenuClassBlacklist = new javax.swing.JPopupMenu();
        jMenuItemDeleteSingle = new javax.swing.JMenuItem();
        jMenuItemDeleteAll = new javax.swing.JMenuItem();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jTextFieldClass = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuItemFileLoad = new javax.swing.JMenuItem();
        jMenuItemFileSave = new javax.swing.JMenuItem();
        jMenuItemFileExit = new javax.swing.JMenuItem();
        jMenuHelp = new javax.swing.JMenu();
        jMenuItemHelpAbout = new javax.swing.JMenuItem();

        jMenuItemDeleteSingle.setLabel("Clear Selected");
        jMenuItemDeleteSingle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDeleteSingleActionPerformed(evt);
            }
        });
        jPopupMenuClassBlacklist.add(jMenuItemDeleteSingle);

        jMenuItemDeleteAll.setLabel("Clear All");
        jMenuItemDeleteAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDeleteAllActionPerformed(evt);
            }
        });
        jPopupMenuClassBlacklist.add(jMenuItemDeleteAll);

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Fixulate Runtime Agent");
        setBounds(new java.awt.Rectangle(200, 200, 200, 200));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Settings"));

        jButton1.setText("Activate Agent");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jList1.setComponentPopupMenu(jPopupMenuClassBlacklist);
        jScrollPane1.setViewportView(jList1);

        jTextFieldClass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ClassKeyPressed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jButton1)
                .add(0, 0, Short.MAX_VALUE))
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                    .add(jTextFieldClass))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jButton1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jTextFieldClass, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 166, Short.MAX_VALUE))
        );

        jMenuFile.setText("File");

        jMenuItemFileLoad.setLabel("Load");
        jMenuItemFileLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFileLoadActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemFileLoad);

        jMenuItemFileSave.setLabel("Save");
        jMenuItemFileSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFileSaveActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemFileSave);

        jMenuItemFileExit.setLabel("Exit");
        jMenuItemFileExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFileExitActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemFileExit);

        jMenuBar1.add(jMenuFile);

        jMenuHelp.setLabel("Help");

        jMenuItemHelpAbout.setLabel("About");
        jMenuHelp.add(jMenuItemHelpAbout);

        jMenuBar1.add(jMenuHelp);

        setJMenuBar(jMenuBar1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
         ArrayList<String> list = new ArrayList();
         for (int i=0; i < blackListClasses.size(); i++) {
            list.add(blackListClasses.get(i).toString());
        }
         
         this.activateInstrumentor(list);
         JOptionPane.showMessageDialog(this, "Agent successfully started.");
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ClassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ClassKeyPressed
         if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            if (!jTextFieldClass.getText().trim().equalsIgnoreCase("")) {
                blackListClasses.add(0,jTextFieldClass.getText().trim());
                jTextFieldClass.setText("");
            }
            
         }
    }//GEN-LAST:event_ClassKeyPressed

    private void jMenuItemDeleteAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDeleteAllActionPerformed
        blackListClasses.clear();
    }//GEN-LAST:event_jMenuItemDeleteAllActionPerformed

    private void jMenuItemDeleteSingleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDeleteSingleActionPerformed
        blackListClasses.removeElement(jList1.getSelectedValue());
    }//GEN-LAST:event_jMenuItemDeleteSingleActionPerformed

    private void jMenuItemFileExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFileExitActionPerformed
        // TODO add your handling code here:
        System.exit(1);
    }//GEN-LAST:event_jMenuItemFileExitActionPerformed

    private void jMenuItemFileLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFileLoadActionPerformed
        fc.showOpenDialog(this);
        File blacklistFile = fc.getSelectedFile();
        JOptionPane.showMessageDialog(this, "Blacklist Loaded");
    }//GEN-LAST:event_jMenuItemFileLoadActionPerformed

    private void jMenuItemFileSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFileSaveActionPerformed
        // TODO add your handling code here:
        fc.showSaveDialog(this);       
        JOptionPane.showMessageDialog(this, "Blacklist Saved");
    }//GEN-LAST:event_jMenuItemFileSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JList jList1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenu jMenuHelp;
    private javax.swing.JMenuItem jMenuItemDeleteAll;
    private javax.swing.JMenuItem jMenuItemDeleteSingle;
    private javax.swing.JMenuItem jMenuItemFileExit;
    private javax.swing.JMenuItem jMenuItemFileLoad;
    private javax.swing.JMenuItem jMenuItemFileSave;
    private javax.swing.JMenuItem jMenuItemHelpAbout;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenuClassBlacklist;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldClass;
    // End of variables declaration//GEN-END:variables
    private final JFileChooser fc = new JFileChooser();
}
